name: PR Actions by Label
description: Runs commands for each label present
branding:
  icon: box
  color: blue
inputs:
  repo-token:
    description: Token with permission to read labels
    required: true
    default: ${{ github.token }}
  items:
    description: |
      An ordered list of labels and commands to run.
      JSON string with represented type `{label: string, run: string}[]`.
      Can repeat labels.
    required: true
    default: "[]"
  case-sensitive:
    description: Whether to treat labels in a case-sensitive manner
    required: false
    default: "false"
runs:
  using: node12
  main: action.js
